# Generated by Django 2.2 on 2019-04-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField()),
                ('death_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.CharField(max_length=50)),
                ('primary_title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('is_adult', models.BooleanField()),
                ('start_year', models.CharField(max_length=10)),
                ('end_year', models.CharField(max_length=10)),
                ('runtime_minutes', models.IntegerField()),
                ('genres', models.ManyToManyField(to='core.Genre')),
                ('title_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Format')),
            ],
        ),
        migrations.CreateModel(
            name='TitleAka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('ttypes', models.CharField(max_length=10)),
                ('attributes', models.CharField(max_length=255)),
                ('is_original_title', models.BooleanField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Language')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.IntegerField()),
                ('number_of_votes', models.IntegerField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('job', models.CharField(max_length=255)),
                ('characters', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Title')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='professions',
            field=models.ManyToManyField(to='core.Profession'),
        ),
        migrations.AddField(
            model_name='person',
            name='titles',
            field=models.ManyToManyField(to='core.Title'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('parent_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_title', to='core.Title')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='core.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directors', models.ManyToManyField(related_name='directors', to='core.Person')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Title')),
                ('writers', models.ManyToManyField(related_name='writers', to='core.Person')),
            ],
        ),
    ]
